// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tehjeblzjyonyjafqvjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlaGplYmx6anlvbnlqYWZxdmp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTUzMzIsImV4cCI6MjA2MzkzMTMzMn0.S5CXol46HRBf1hPlTcST2XliH7t8c3ZqgG7kN_RPZnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);